name: "push-to-ghcr"
author: "@macbre"
description: "This action simplifies pushes of Docker images ot ghcr.io repository"
# https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#branding
branding:
  icon: "arrow-up-circle"
  color: "blue"
  
inputs:
  github_token: 
     description: "Your secrets.GITHUB_TOKEN"
     required: true

  image_name:
    description: "Image name, e.g. my-user-name/my-repo"
    required: true

  repository:
    description: "Docker repository to push an image to, defaults to ghcr.io"
    required: true
    default: "ghcr.io"

  docker_io_token:
    description: "Your docker.io token created via https://hub.docker.com/settings/security"
    required: false

runs:
  using: "composite"
  steps:
    # https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-container-registry#authenticating-to-the-container-registry
    - name: Log in to the Container registry
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
      run: |
        echo "${GITHUB_TOKEN}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin

    - name: Set commit tag and image name
      shell: bash
      run: |
        echo "::group::Set commit tag and image name"      
        if [ "${{ github.event_name }}" = "release" ]; then
          export COMMIT_TAG=${GITHUB_REF:10}
          # export COMMIT_TAG=v2.3.0 # debug
          echo "COMMIT_TAG=${COMMIT_TAG//v/}" >> $GITHUB_ENV # remove "v" suffix
        else
          echo "COMMIT_TAG=latest" >> $GITHUB_ENV
        fi
        echo "::endgroup::"

    - name: "Build the Docker image"
      shell: bash
      run: |
        echo "::group::Build the Docker image"

        # expand commands
        set -x

        docker -v

        export BUILD_DATE=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
        export GITHUB_URL=https://github.com/${{ github.repository }}

        echo
        echo "Building the Docker image: ${{ inputs.repository }}/${{ inputs.image_name }}:${{ env.COMMIT_TAG }} ..."
        echo

        # https://docs.docker.com/develop/develop-images/build_enhancements/
        # https://docs.docker.com/engine/reference/commandline/build/#specifying-external-cache-sources
        DOCKER_BUILDKIT=1 \
          docker build . \
          --cache-from ${{ inputs.repository }}/${{ inputs.image_name }}:latest \
          --build-arg BUILDKIT_INLINE_CACHE=1 \
          \
          --build-arg BUILD_DATE=${BUILD_DATE} \
          --build-arg GITHUB_SHA=${GITHUB_SHA} \
          \
          --tag ${{ inputs.repository }}/${{ inputs.image_name }}:${{ env.COMMIT_TAG }} \
          --tag docker.io/${{ inputs.image_name }}:${{ env.COMMIT_TAG }} \
          \
          --label org.label-schema.build-date=${BUILD_DATE} \
          --label org.label-schema.vcs-url=${GITHUB_URL} \
          --label org.label-schema.vcs-ref=${GITHUB_SHA} \
          \
          --label org.opencontainers.image.created=${BUILD_DATE} \
          --label org.opencontainers.image.source=${GITHUB_URL} \
          --label org.opencontainers.image.revision=${GITHUB_SHA}
        echo "::endgroup::"

        echo "::group::Inspecting the image"
        docker images
        docker image inspect ${{ inputs.repository }}/${{ inputs.image_name }}:${{ env.COMMIT_TAG }} | jq '.[].Config.Labels'
        echo "::endgroup::"

    - name: "Push the Docker image to ghcr.io"
      shell: bash
      run: |
        echo "::group::Pushing the Docker image to ghcr.io ..."

        # expand commands
        set -x

        docker push --quiet ${{ inputs.repository }}/${{ inputs.image_name }}:${{ env.COMMIT_TAG }}
        echo "::endgroup::"

    - name: "Push the Docker image to docker.io"
      shell: bash
      env:
        DOCKER_TOKEN: ${{ inputs.docker_io_token }}
      run: |
        if [ -z "${DOCKER_TOKEN}" ]; then
          echo "::warning::NOT pushing the Docker image to docker.io ... Provide 'docker_io_token' if needed."
        else
          echo "::group::Pushing the Docker image to docker.io ..."

          # expand commands
          set -x

          echo "${DOCKER_TOKEN}" | docker login docker.io -u "${{ github.actor }}" --password-stdin

          docker push --quiet docker.io/${{ inputs.image_name }}:${{ env.COMMIT_TAG }}
          echo "::endgroup::"
        fi
