name: "push-to-ghcr"
author: "@macbre"
description: "This action simplifies pushes of Docker images ot ghcr.io repository"
# https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#branding
branding:
  icon: "arrow-up-circle"
  color: "blue"

runs:
  using: "composite"
  steps:

    # https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-container-registry#authenticating-to-the-container-registry
    - name: Log in to the Container registry
      shell: bash
      run: |
        echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Set commit tag
      shell: bash
      run: |
        if [ "${{ github.event_name }}" = "release" ]; then
          export COMMIT_TAG=${GITHUB_REF:10}
          # export COMMIT_TAG=v2.3.0 # debug
          echo "COMMIT_TAG=${COMMIT_TAG//v/}" >> $GITHUB_ENV # remove "v" suffix
        else
          echo "COMMIT_TAG=latest" >> $GITHUB_ENV
        fi

    - name: Show env variables
      shell: bash
      run: env | sort

    - name: "Build the Docker image (tag: ${{ env.COMMIT_TAG }}, event: ${{ github.event_name }})"
      shell: bash
      run: |
        COMPOSE_DOCKER_CLI_BUILD=1 DOCKER_BUILDKIT=1 \
          docker build . \
          --cache-from ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest \
          --build-arg GITHUB_SHA=${GITHUB_SHA}
          --tag ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.COMMIT_TAG }}
          
    - name: Inspect an image
      shell: bash
      run: |
        docker images | head -n3
        docker inspect --format='{{json .Config.Labels}}' ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.COMMIT_TAG }} | jq
