name: "push-to-ghcr"
author: "@macbre"
description: "This action simplifies pushes of Docker images ot ghcr.io repository"
# https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#branding
branding:
  icon: "arrow-up-circle"
  color: "blue"
  
inputs:
  github_token: 
     description: "Your secrets.GITHUB_TOKEN"
     required: true

  image_name:
    description: "Image name, e.g. my-user-name/my-repo"
    required: true

  repository:
    description: "Docker repository to push an image to, defaults to ghcr.io"
    required: true
    default: "ghcr.io"

runs:
  using: "composite"
  steps:
    # https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-container-registry#authenticating-to-the-container-registry
    - name: Log in to the Container registry
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
      run: |
        echo "${GITHUB_TOKEN}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin

    - name: Set commit tag and image name
      shell: bash
      run: |
        if [ "${{ github.event_name }}" = "release" ]; then
          export COMMIT_TAG=${GITHUB_REF:10}
          # export COMMIT_TAG=v2.3.0 # debug
          echo "COMMIT_TAG=${COMMIT_TAG//v/}" >> $GITHUB_ENV # remove "v" suffix
        else
          echo "COMMIT_TAG=latest" >> $GITHUB_ENV
        fi

    - name: Show env variables
      shell: bash
      run: env | sort

    - name: "Build and push the Docker image"
      shell: bash
      run: |
        # expand commands
        set -x

        export BUILD_DATE=$(date -u +"%Y-%m-%dT%H:%M:%SZ")

        echo
        echo "Building the Docker image: ${{ inputs.repository }}/${{ inputs.image_name }}:${{ env.COMMIT_TAG }} ..."
        echo

        COMPOSE_DOCKER_CLI_BUILD=1 DOCKER_BUILDKIT=1 \
          docker build . \
          --cache-from ${{ inputs.repository }}/${{ inputs.image_name }}:latest \
          \
          --build-arg BUILD_DATE=${BUILD_DATE} \
          --build-arg GITHUB_SHA=${GITHUB_SHA} \
          \
          --tag ${{ inputs.repository }}/${{ inputs.image_name }}:${{ env.COMMIT_TAG }} \
          --tag ${{ inputs.image_name }} \
          \
          --label org.label-schema.build-date=${BUILD_DATE} \
          --label org.label-schema.vcs-url=https://github.com/${{ inputs.image_name }}.git \
          --label org.label-schema.vcs-ref=${GITHUB_SHA}

        echo
        echo "Pushing the Docker image ..."
        echo

        docker push ${{ inputs.repository }}/${{ inputs.image_name }}:${{ env.COMMIT_TAG }}
        
        echo
        echo "Inspecting the image ..."
        echo

        docker images | head -n3
        docker image inspect --format='{{json .Config}}' ${{ inputs.image_name }}
