name: CI
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  ci:
    runs-on: "ubuntu-20.04"  # https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on

    steps:
      - uses: actions/checkout@v2

      - name: Run an action
        uses: ./
