name: CI
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  ci:
    runs-on: "ubuntu-20.04"  # https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on

    steps:
      - uses: actions/checkout@v2

      - name: Run an action
        uses: ./
        with:
          image_name: ${{ github.repository }}
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Make sure that an image has been pushed and is properly labelled
        env:
          IMAGE: ghcr.io/${{ github.repository }}
        run: |
          docker pull ${IMAGE}
          docker image inspect ${IMAGE} | jq '.[].Config.Labels' | grep "${GITHUB_SHA}"
